package state

import (
	"path/filepath"
	"strings"
)

type StateDomainID string

const (
	StateDomainCommsState            StateDomainID = "comms_state"
	StateDomainTrustStore            StateDomainID = "trust_store"
	StateDomainTrustHistory          StateDomainID = "trust_history"
	StateDomainCandidateStore        StateDomainID = "candidate_store"
	StateDomainSidecarGeneratedState StateDomainID = "sidecar_generated_state"
	StateDomainSidecarBuildOutput    StateDomainID = "sidecar_build_output"
	StateDomainLocalCypherDB         StateDomainID = "local_cypher_db"
)

type VaultClass string

const (
	VaultClassLocalAppState          VaultClass = "local_app_state"
	VaultClassLocalTrustState        VaultClass = "local_trust_state"
	VaultClassAppendOnlyTrustHistory VaultClass = "append_only_trust_history"
	VaultClassTrustAdjacentCandidate VaultClass = "trust_adjacent_candidate_state"
	VaultClassGeneratedSecretState   VaultClass = "generated_secret_state"
	VaultClassGeneratedBuildOutput   VaultClass = "generated_build_output"
	VaultClassServerRelayLocalState  VaultClass = "server_relay_local_state"
)

type StateDomainDefinition struct {
	ID                  StateDomainID
	Classification      string
	VaultClass          VaultClass
	SecretBearing       string
	FutureVaultRequired bool
	SafeToPrintContents bool
	SafeToDelete        string
	MutationAllowed     bool
	Note                string
}

type StateDomainResolution struct {
	Domain StateDomainDefinition
	Path   string
}

func ResolveDefaultStateDomains(opts StateAuditOptions) []StateDomainResolution {
	opts = normalizeStateAuditOptions(opts)

	stateDir := filepath.Dir(opts.StatePath)
	if stateDir == "." || strings.TrimSpace(stateDir) == "" {
		stateDir = "."
	}

	return []StateDomainResolution{
		{
			Domain: StateDomainDefinition{
				ID:                  StateDomainCommsState,
				Classification:      "local-app-state",
				VaultClass:          VaultClassLocalAppState,
				SecretBearing:       "maybe",
				FutureVaultRequired: true,
				SafeToPrintContents: false,
				SafeToDelete:        "no",
				MutationAllowed:     false,
				Note:                "contains local Comms account/device/server configuration; do not print raw contents in audits",
			},
			Path: opts.StatePath,
		},
		{
			Domain: StateDomainDefinition{
				ID:                  StateDomainTrustStore,
				Classification:      "local-trust-state",
				VaultClass:          VaultClassLocalTrustState,
				SecretBearing:       "maybe",
				FutureVaultRequired: true,
				SafeToPrintContents: false,
				SafeToDelete:        "no",
				MutationAllowed:     false,
				Note:                "client-owned trust state; provider observation, Relay Space routing, and OpenMLS membership must not silently mutate it",
			},
			Path: filepath.Join(stateDir, "trust.json"),
		},
		{
			Domain: StateDomainDefinition{
				ID:                  StateDomainTrustHistory,
				Classification:      "append-only-trust-history",
				VaultClass:          VaultClassAppendOnlyTrustHistory,
				SecretBearing:       "maybe",
				FutureVaultRequired: true,
				SafeToPrintContents: false,
				SafeToDelete:        "no",
				MutationAllowed:     false,
				Note:                "append-only local trust/history evidence; important for recovery and mismatch review",
			},
			Path: filepath.Join(stateDir, "trust-events.jsonl"),
		},
		{
			Domain: StateDomainDefinition{
				ID:                  StateDomainCandidateStore,
				Classification:      "local-trust-adjacent-candidate-state",
				VaultClass:          VaultClassTrustAdjacentCandidate,
				SecretBearing:       "maybe",
				FutureVaultRequired: true,
				SafeToPrintContents: false,
				SafeToDelete:        "no",
				MutationAllowed:     false,
				Note:                "unverified/candidate identity material; never equivalent to verified trust",
			},
			Path: filepath.Join(stateDir, "identity-candidates.json"),
		},
		{
			Domain: StateDomainDefinition{
				ID:                  StateDomainSidecarGeneratedState,
				Classification:      "generated-dev-provider-state",
				VaultClass:          VaultClassGeneratedSecretState,
				SecretBearing:       "yes",
				FutureVaultRequired: true,
				SafeToPrintContents: false,
				SafeToDelete:        "only explicit generated-state cleanup, never unknown operator state",
				MutationAllowed:     false,
				Note:                "dev-local OpenMLS signer/provider/group state; not production vault storage",
			},
			Path: opts.SidecarStateRoot,
		},
		{
			Domain: StateDomainDefinition{
				ID:                  StateDomainSidecarBuildOutput,
				Classification:      "generated-build-output",
				VaultClass:          VaultClassGeneratedBuildOutput,
				SecretBearing:       "no",
				FutureVaultRequired: false,
				SafeToPrintContents: false,
				SafeToDelete:        "yes if generated by local build",
				MutationAllowed:     false,
				Note:                "Rust/Cargo build output; excluded from release material",
			},
			Path: opts.SidecarTargetRoot,
		},
		{
			Domain: StateDomainDefinition{
				ID:                  StateDomainLocalCypherDB,
				Classification:      "server-relay-local-db",
				VaultClass:          VaultClassServerRelayLocalState,
				SecretBearing:       "maybe",
				FutureVaultRequired: false,
				SafeToPrintContents: false,
				SafeToDelete:        "only explicit local operator cleanup",
				MutationAllowed:     false,
				Note:                "local Cypher SQLite database may contain relay metadata/envelopes; not Comms vault state and not release material",
			},
			Path: opts.CypherDBPath,
		},
	}
}
